name: Update Main README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update README
        run: |
          import os
          
          def get_folder_readme(folder):
              readme_path = os.path.join(folder, 'README.md')
              if os.path.exists(readme_path):
                  with open(readme_path, 'r') as f:
                      return f.read().strip()
              return "No README found in this folder."
          
          main_readme = "# Project Overview\n\n This repository is to store my presentations."
          
          for item in os.listdir('.'):
              if os.path.isdir(item) and not item.startswith('.'):
                  main_readme += f"´´´"
                  main_readme += f"# {item}\n\n"
                  main_readme += get_folder_readme(item)
                  main_readme += "\n\n"
                  main_readme += f"´´´"
          
          with open('README.md', 'w') as f:
              f.write(main_readme)
        shell: python

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update main README.md with folder contents" && git push)